onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /soc_tb_v1/uut/iSoC/clk
add wave -noupdate /soc_tb_v1/uut/iSoC/resetn
add wave -noupdate /soc_tb_v1/uut/iSoC/halt
add wave -noupdate /soc_tb_v1/uut/iSoC/misaligned_fetch
add wave -noupdate /soc_tb_v1/uut/iSoC/iomem_valid
add wave -noupdate /soc_tb_v1/uut/iSoC/iomem_ready
add wave -noupdate /soc_tb_v1/uut/iSoC/iomem_wstrb
add wave -noupdate /soc_tb_v1/uut/iSoC/iomem_addr
add wave -noupdate /soc_tb_v1/uut/iSoC/iomem_wdata
add wave -noupdate /soc_tb_v1/uut/iSoC/iomem_rdata
add wave -noupdate /soc_tb_v1/uut/iSoC/ser_tx
add wave -noupdate /soc_tb_v1/uut/iSoC/ser_rx
add wave -noupdate /soc_tb_v1/uut/iSoC/flash_csb
add wave -noupdate /soc_tb_v1/uut/iSoC/flash_clk
add wave -noupdate /soc_tb_v1/uut/iSoC/flash_io0_oe
add wave -noupdate /soc_tb_v1/uut/iSoC/flash_io1_oe
add wave -noupdate /soc_tb_v1/uut/iSoC/flash_io2_oe
add wave -noupdate /soc_tb_v1/uut/iSoC/flash_io3_oe
add wave -noupdate /soc_tb_v1/uut/iSoC/flash_io0_do
add wave -noupdate /soc_tb_v1/uut/iSoC/flash_io1_do
add wave -noupdate /soc_tb_v1/uut/iSoC/flash_io2_do
add wave -noupdate /soc_tb_v1/uut/iSoC/flash_io3_do
add wave -noupdate /soc_tb_v1/uut/iSoC/flash_io0_di
add wave -noupdate /soc_tb_v1/uut/iSoC/flash_io1_di
add wave -noupdate /soc_tb_v1/uut/iSoC/flash_io2_di
add wave -noupdate /soc_tb_v1/uut/iSoC/flash_io3_di
add wave -noupdate /soc_tb_v1/uut/iSoC/mem_valid
add wave -noupdate /soc_tb_v1/uut/iSoC/mem_ready
add wave -noupdate /soc_tb_v1/uut/iSoC/mem_addr
add wave -noupdate /soc_tb_v1/uut/iSoC/mem_wdata
add wave -noupdate /soc_tb_v1/uut/iSoC/mem_wstrb
add wave -noupdate /soc_tb_v1/uut/iSoC/mem_rdata
add wave -noupdate /soc_tb_v1/uut/iSoC/spimem_ready
add wave -noupdate /soc_tb_v1/uut/iSoC/spimem_rdata
add wave -noupdate /soc_tb_v1/uut/iSoC/ram_ready
add wave -noupdate /soc_tb_v1/uut/iSoC/ram_rdata
add wave -noupdate /soc_tb_v1/uut/iSoC/iomem_ready_ff
add wave -noupdate /soc_tb_v1/uut/iSoC/iomem_valid_ff
add wave -noupdate /soc_tb_v1/uut/iSoC/spimemio_cfgreg_sel
add wave -noupdate /soc_tb_v1/uut/iSoC/spimemio_cfgreg_do
add wave -noupdate /soc_tb_v1/uut/iSoC/simpleuart_reg_div_sel
add wave -noupdate /soc_tb_v1/uut/iSoC/simpleuart_reg_div_do
add wave -noupdate /soc_tb_v1/uut/iSoC/simpleuart_reg_dat_sel
add wave -noupdate /soc_tb_v1/uut/iSoC/simpleuart_reg_dat_do
add wave -noupdate /soc_tb_v1/uut/iSoC/simpleuart_reg_dat_wait
add wave -noupdate /soc_tb_v1/uut/iSoC/spimemio_cfgreg_sel_ff
add wave -noupdate /soc_tb_v1/uut/iSoC/simpleuart_reg_div_sel_ff
add wave -noupdate /soc_tb_v1/uut/iSoC/simpleuart_reg_dat_sel_ff
add wave -noupdate /soc_tb_v1/uut/iSoC/pc_fetch
add wave -noupdate /soc_tb_v1/uut/iSoC/instruction
add wave -noupdate /soc_tb_v1/uut/iSoC/data_addr
add wave -noupdate /soc_tb_v1/uut/iSoC/data_store
add wave -noupdate /soc_tb_v1/uut/iSoC/data_fetch
add wave -noupdate /soc_tb_v1/uut/iSoC/data_enable
add wave -noupdate /soc_tb_v1/uut/iSoC/data_read
add wave -noupdate /soc_tb_v1/uut/iSoC/flush
add wave -noupdate /soc_tb_v1/uut/iSoC/branch
add wave -noupdate /soc_tb_v1/uut/iSoC/stall
add wave -noupdate /soc_tb_v1/uut/iSoC/busy
add wave -noupdate /soc_tb_v1/uut/iSoC/wb_result
add wave -noupdate /soc_tb_v1/uut/iSoC/UART_data
add wave -noupdate /soc_tb_v1/uut/iSoC/UART_config
add wave -noupdate /soc_tb_v1/uut/iSoC/SPI_config
add wave -noupdate /soc_tb_v1/uut/iSoC/External_IO
add wave -noupdate /soc_tb_v1/uut/iSoC/SRAM0_out
add wave -noupdate /soc_tb_v1/uut/iSoC/SRAM1_out
add wave -noupdate /soc_tb_v1/uut/iSoC/SRAM2_out
add wave -noupdate /soc_tb_v1/uut/iSoC/SRAM3_out
add wave -noupdate /soc_tb_v1/uut/iSoC/SRAM_select
add wave -noupdate /soc_tb_v1/uut/iSoC/SRAM_select_ff
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {245000 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {911288 ps} {1452038 ps}
