onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /rv32_system_tb/iSoC/iCPU/clk
add wave -noupdate /rv32_system_tb/iSoC/iCPU/rst_n
add wave -noupdate /rv32_system_tb/iSoC/iCPU/pc_fetch
add wave -noupdate /rv32_system_tb/iSoC/iCPU/code_fetch
add wave -noupdate /rv32_system_tb/iSoC/iCPU/data_enable
add wave -noupdate /rv32_system_tb/iSoC/iCPU/data_read
add wave -noupdate /rv32_system_tb/iSoC/iCPU/data_addr
add wave -noupdate /rv32_system_tb/iSoC/iCPU/data_store
add wave -noupdate /rv32_system_tb/iSoC/iCPU/data_fetch
add wave -noupdate /rv32_system_tb/iSoC/iCPU/flush
add wave -noupdate /rv32_system_tb/iSoC/iCPU/stall
add wave -noupdate /rv32_system_tb/iSoC/iCPU/halt
add wave -noupdate /rv32_system_tb/iSoC/iCPU/wb_result
add wave -noupdate /rv32_system_tb/iSoC/iCPU/decode_code_bus
add wave -noupdate /rv32_system_tb/iSoC/iCPU/decode_pc
add wave -noupdate /rv32_system_tb/iSoC/iCPU/decode_pc_ret
add wave -noupdate /rv32_system_tb/iSoC/iCPU/pc_branch
add wave -noupdate /rv32_system_tb/iSoC/iCPU/decode_pc_ctrl
add wave -noupdate /rv32_system_tb/iSoC/iCPU/decode_alu_ctrl
add wave -noupdate /rv32_system_tb/iSoC/iCPU/decode_bshift_ctrl
add wave -noupdate /rv32_system_tb/iSoC/iCPU/decode_rf_ctrl
add wave -noupdate /rv32_system_tb/iSoC/iCPU/decode_data_ctrl
add wave -noupdate /rv32_system_tb/iSoC/iCPU/decode_rs1
add wave -noupdate /rv32_system_tb/iSoC/iCPU/decode_rs2
add wave -noupdate /rv32_system_tb/iSoC/iCPU/execute_code_bus
add wave -noupdate /rv32_system_tb/iSoC/iCPU/execute_pc
add wave -noupdate /rv32_system_tb/iSoC/iCPU/execute_rs1
add wave -noupdate /rv32_system_tb/iSoC/iCPU/execute_rs2
add wave -noupdate /rv32_system_tb/iSoC/iCPU/execute_pc_ret
add wave -noupdate /rv32_system_tb/iSoC/iCPU/execute_alu_ctrl
add wave -noupdate /rv32_system_tb/iSoC/iCPU/execute_bshift_ctrl
add wave -noupdate /rv32_system_tb/iSoC/iCPU/execute_data_ctrl
add wave -noupdate /rv32_system_tb/iSoC/iCPU/execute_rf_ctrl
add wave -noupdate /rv32_system_tb/iSoC/iCPU/execute_pc_hlt
add wave -noupdate /rv32_system_tb/iSoC/iCPU/RS1_EX2EX
add wave -noupdate /rv32_system_tb/iSoC/iCPU/RS2_EX2EX
add wave -noupdate /rv32_system_tb/iSoC/iCPU/RS1_Mem2EX
add wave -noupdate /rv32_system_tb/iSoC/iCPU/RS2_Mem2EX
add wave -noupdate /rv32_system_tb/iSoC/iCPU/RS1_Mem2Mem
add wave -noupdate /rv32_system_tb/iSoC/iCPU/operandA
add wave -noupdate /rv32_system_tb/iSoC/iCPU/operandB
add wave -noupdate /rv32_system_tb/iSoC/iCPU/execute_alu_res
add wave -noupdate /rv32_system_tb/iSoC/iCPU/execute_comp_res
add wave -noupdate /rv32_system_tb/iSoC/iCPU/execute_bshift_res
add wave -noupdate /rv32_system_tb/iSoC/iCPU/memory_data_store
add wave -noupdate /rv32_system_tb/iSoC/iCPU/memory_code_bus
add wave -noupdate /rv32_system_tb/iSoC/iCPU/memory_pc_ret
add wave -noupdate /rv32_system_tb/iSoC/iCPU/memory_alu_res
add wave -noupdate /rv32_system_tb/iSoC/iCPU/memory_bshift_res
add wave -noupdate /rv32_system_tb/iSoC/iCPU/memory_rf_ctrl
add wave -noupdate /rv32_system_tb/iSoC/iCPU/memory_data_ctrl
add wave -noupdate /rv32_system_tb/iSoC/iCPU/memory_pc_hlt
add wave -noupdate /rv32_system_tb/iSoC/iCPU/wb_code_bus
add wave -noupdate /rv32_system_tb/iSoC/iCPU/wb_pc_ret
add wave -noupdate /rv32_system_tb/iSoC/iCPU/wb_alu_res
add wave -noupdate /rv32_system_tb/iSoC/iCPU/wb_bshift_res
add wave -noupdate /rv32_system_tb/iSoC/iCPU/wb_data_res
add wave -noupdate /rv32_system_tb/iSoC/iCPU/wb_rf_ctrl
add wave -noupdate /rv32_system_tb/iSoC/iCPU/wb_pc_hlt
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {140000 ps} 0} {{Cursor 2} {100000 ps} 0}
quietly wave cursor active 2
configure wave -namecolwidth 296
configure wave -valuecolwidth 98
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {194250 ps}
