onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/clk
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/rst_n
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/pc_fetch
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/code_fetch
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/data_enable
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/data_read
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/data_addr
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/data_store
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/data_fetch
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/flush
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/branch
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/stall
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/busy
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/halt
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/wb_result
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/decode_code_bus
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/decode_pc
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/decode_pc_ret
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/pc_branch
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/decode_pc_ctrl
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/decode_alu_ctrl
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/decode_bshift_ctrl
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/decode_rf_ctrl
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/decode_data_ctrl
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/decode_sel_rs1
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/decode_sel_rs2
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/decode_sel_rd1
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/decode_rs1
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/decode_rs2
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/load_to_use_stall
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/internal_stall
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/execute_code_bus
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/execute_pc
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/execute_rs1
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/execute_rs2
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/execute_pc_ret
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/execute_alu_ctrl
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/execute_bshift_ctrl
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/execute_data_ctrl
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/execute_rf_ctrl
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/execute_pc_hlt
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/execute_sel_rs1
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/execute_sel_rs2
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/execute_sel_rd1
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/execute_alu_res
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/OperandA
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/OperandB
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/RS1_EX2EX
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/RS2_EX2EX
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/RS2_Mem2EX
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/RS1_Mem2EX
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/RS1_Mem2Mem
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/memory_data_store
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/memory_code_bus
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/memory_pc_ret
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/memory_alu_res
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/memory_sel_rd1
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/memory_rf_ctrl
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/memory_data_ctrl
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/memory_pc_hlt
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/wb_code_bus
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/wb_pc_ret
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/wb_alu_res
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/wb_data_res
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/wb_sel_rd1
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/wb_rf_ctrl
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/wb_pc_hlt
add wave -noupdate /soc_tb_v1/uut/iSoC/iCPU/execute_pc_ctrl
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {290000 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 215
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {1360786 ps} {1428380 ps}
