//---------------------------------------------------------------------
//               Copyright(c) Synopsys, Inc.                           
//     All Rights reserved - Unpublished -rights reserved under        
//     the Copyright laws of the United States of America.             
//                                                                     
//  U.S. Patents: 7,093,156 B1 and 7,406,620 B2 (and more pending).    
//                                                                     
//  This file includes the Confidential information of Synopsys, Inc.  
//  and GF.                                                            
//  The receiver of this Confidential Information shall not disclose   
//  it to any third party and shall protect its confidentiality by     
//  using the same degree of care, but not less than a reasonable      
//  degree of care, as the receiver uses to protect receiver's own     
//  Confidential Information.                                          
//  Licensee acknowledges and agrees that all output generated for     
//  Licensee by Synopsys, Inc. as described in the pertinent Program   
//  Schedule(s), or generated by Licensee through use of any Compiler  
//  licensed hereunder contains information that complies with the     
//  Virtual Component Identification Physical Tagging Standard (VCID)  
//  as maintained by the Virtual Socket Interface Alliance (VSIA).     
//  Such information may be expressed in GDSII Layer 63 or other such  
//  layer designated by the VSIA, hardware definition languages, or    
//  other formats.  Licensee is not authorized to alter or change any  
//  such information.                                                  
//---------------------------------------------------------------------
//                                                                     
//  Built for linux64 and running on linux64.                          
//                                                                     
//  Software           : Rev: W-2024.12-SP1                            
//  Library Format     : Rev: 1.05.00                                  
//  Compiler Name      : gf22nsd81p11saduv02msa03p1                    
//  Platform           : Linux6.1.0-40-amd64                           
//                     : #1 SMP PREEMPT_DYNAMIC Debian 6.1.153-1 (2025-09-20)x86_64
//  Date of Generation : Wed Oct 22 23:46:11 CDT 2025                  
//                                                                     
//---------------------------------------------------------------------
//   --------------------------------------------------------------     
//                       Template Revision : 6.7.0                      
//   --------------------------------------------------------------     
//                      * Synchronous, 1-Port SRAM *                  
//                    * Core used by Emulation Model *                
//                THIS IS A SYNCHRONOUS 1-PORT MEMORY MODEL           
//                                                                    
//   Memory Name:saduvssd8ULTRALOW1p4096x32m16b1w1c1p1d0l0rm3sdrw11   
//   Memory Size:4096 words x 32 bits                                 
//                                                                    
//                               PORT NAME                            
//                               ---------                            
//               Output Ports                                         
//                                   Q[31:0]                          
//               Input Ports:                                         
//                                   ADR[11:0]                        
//                                   D[31:0]                          
//                                   WEM[31:0]                        
//                                   WE                               
//                                   ME                               
//                                   CLK                              
// -------------------------------------------------------------------- 


module saduvssd8ULTRALOW1p4096x32m16b1w1c1p1d0l0rm3sdrw11_core ( Q, ADR, D, WEM, WE, ME, CLK);

output [31:0] Q;
input [11:0] ADR;
input [31:0] D;
input [31:0] WEM;
input WE;
input ME;
input CLK;


// behavior to be replaced by actual SRAM in VLE

reg [31:0] ram_core [4095:0];

reg [31:0] Q_tmp;

always @(posedge CLK)
begin
  if ( ME && WE )
    ram_core[ADR] = (ram_core[ADR] & (~WEM)) | (D & WEM);
  if ( ME && !WE )
    Q_tmp <= ram_core[ADR];
end

assign Q = Q_tmp;


endmodule
