### File List for RTL Compilation for IVM SOC
### Split into segments that handle each block

### IVM Custom RISC-V CPU: RV32I
$SOC_HOME/Designs/CPU/branch_resolver_v2.sv
$SOC_HOME/Designs/CPU/interrupt_handler.sv
$SOC_HOME/Designs/CPU/rv32_alu_add_sub.sv
$SOC_HOME/Designs/CPU/rv32_alu_comp.sv
$SOC_HOME/Designs/CPU/rv32_alu_logical.sv
$SOC_HOME/Designs/CPU/rv32_barrel_shifter.sv
$SOC_HOME/Designs/CPU/rv32_alu_v2.sv
$SOC_HOME/Designs/CPU/rv32_cu_v2.sv
$SOC_HOME/Designs/CPU/rv32_if_id_queue.sv
$SOC_HOME/Designs/CPU/rv32_id_ex_queue.sv
$SOC_HOME/Designs/CPU/rv32_ex_mem_queue.sv
$SOC_HOME/Designs/CPU/rv32_mem_wb_queue.sv
$SOC_HOME/Designs/CPU/write_back.sv
$SOC_HOME/Designs/CPU/rv32_pc_v2.sv
$SOC_HOME/Designs/CPU/rv32_register_file.sv
$SOC_HOME/Designs/CPU/forwarding_unit_v2.sv
$SOC_HOME/Designs/CPU/hazard_detection.sv
$SOC_HOME/Designs/CPU/rv32_cpu_top.sv

### Memory Subsystems: Cache & SRAMs
### SRAMs as generated by the Embedit Integrator Tool
### 128 Byte SRAM: 32x32
$SOC_HOME/Designs/Memory/SRAMs/saduvssd8ULTRALOW1p32x32m2b1w0c0p0d0l0rm3sdrw01_core.v
### 256 Byte SRAM: 256x8
$SOC_HOME/Designs/Memory/SRAMs/saduvssd8ULTRALOW1p256x8m4b1w0c0p0d0l0rm3sdrw01_core.v
### 1K Byte SRAM: 256x32
$SOC_HOME/Designs/Memory/SRAMs/saduvssd8ULTRALOW1p256x32m8b1w0c0p0d0l0rm3sdrw01_core.v
### 2K Byte SRAM: 512x32
$SOC_HOME/Designs/Memory/SRAMs/saduvssd8ULTRALOW1p512x32m16b1w0c1p1d0l0rm3sdrw11_core.v
$SOC_HOME/Designs/Memory/SRAMs/saduvssd8ULTRALOW1p512x32m16b1w1c1p1d0l0rm3sdrw11_core.v
### 4K Byte SRAM: 1024x32
$SOC_HOME/Designs/Memory/SRAMs/saduvssd8ULTRALOW1p1024x32m16b1w0c1p1d0l0rm3sdrw11_core.v
$SOC_HOME/Designs/Memory/SRAMs/saduvssd8ULTRALOW1p1024x32m16b1w1c1p1d0l0rm3sdrw11_core.v
### 8K Byte SRAM: 2048x32
$SOC_HOME/Designs/Memory/SRAMs/saduvssd8ULTRALOW1p2048x32m16b1w0c1p1d0l0rm3sdrw11_core.v
$SOC_HOME/Designs/Memory/SRAMs/saduvssd8ULTRALOW1p2048x32m16b1w1c1p1d0l0rm3sdrw11_core.v
### 16K Byte SRAM: 4096x32
$SOC_HOME/Designs/Memory/SRAMs/saduvssd8ULTRALOW1p4096x32m16b1w0c1p1d0l0rm3sdrw11_core.v
$SOC_HOME/Designs/Memory/SRAMs/saduvssd8ULTRALOW1p4096x32m16b1w1c1p1d0l0rm3sdrw11_core.v
### 32K Byte SRAM: 4096x64
$SOC_HOME/Designs/Memory/SRAMs/saduvssd8ULTRALOW1p4096x64m16b1w1c1p1d0l0rm3sdrw11_core.v
### 128K Byte SRAM: 32768x32
$SOC_HOME/Designs/Memory/SRAMs/saduvssd8ULTRALOW1p32768x32m16b8w0c1p0d0l0rm3sdrw11_core.v
$SOC_HOME/Designs/Memory/SRAMs/saduvssd8ULTRALOW1p32768x32m16b8w1c1p0d0l0rm3sdrw11_core.v
### 256K Byte SRAM: 32768x64
$SOC_HOME/Designs/Memory/SRAMs/saduvssd8ULTRALOW1p32768x64m16b8w0c1p0d0l0rm3sdrw11_core.v
$SOC_HOME/Designs/Memory/SRAMs/saduvssd8ULTRALOW1p32768x64m16b8w1c1p0d0l0rm3sdrw11_core.v

### Cache Wrappers using the above SRAMs
### L1 Caches
$SOC_HOME/Designs/Memory/Cache/i_cache_v1.sv
$SOC_HOME/Designs/Memory/Cache/d_cache_v1.sv

$SOC_HOME/Designs/Memory/Cache/i_cache_v2.sv
$SOC_HOME/Designs/Memory/Cache/d_cache_v2.sv

### L2 Caches
$SOC_HOME/Designs/Memory/Cache/level_2_cache_v1.sv

### Cache Controllers
$SOC_HOME/Designs/Memory/Cache/cache_controller_v1.sv
$SOC_HOME/Designs/Memory/Cache/cache_controller_v2.sv

### Peripherals: Perfmons, GPIO, UART, SPI, MMIO Decoders, etc
$SOC_HOME/Designs/IO/perfmons.sv
$SOC_HOME/Designs/IO/gpio_v1.sv
$SOC_HOME/Designs/IO/spiflash.v
$SOC_HOME/Designs/IO/spimemio.v
$SOC_HOME/Designs/IO/UART_rx.sv
$SOC_HOME/Designs/IO/UART_tx.sv
$SOC_HOME/Designs/IO/UART.sv
$SOC_HOME/Designs/IO/UART_v1.sv
$SOC_HOME/Designs/IO/mmio_decoder_v1.sv

### CIM Module: Custom Block by Sun Miao, UW Madison
# $SOC_HOME/Designs/CIM/accumulator.sv
# $SOC_HOME/Designs/CIM/Adder_tree.sv
# $SOC_HOME/Designs/CIM/carry_processing.sv
# $SOC_HOME/Designs/CIM/FindMax_tree.sv
# $SOC_HOME/Designs/CIM/fp8_Decoder.sv
# $SOC_HOME/Designs/CIM/Split_decoder.sv
# $SOC_HOME/Designs/CIM/Timing.sv
# $SOC_HOME/Designs/CIM/CIM_Compute.sv
# $SOC_HOME/Designs/CIM/CIM_FP.sv
# $SOC_HOME/Designs/CIM/CIM_Input.sv
# $SOC_HOME/Designs/CIM/CIM.sv
# $SOC_HOME/Designs/CIM/CIM_TOP_reconstruct.sv
# $SOC_HOME/Designs/CIM/CIM_TOP_WRAPPER.sv

### Top Level Instantiations of the SOC as a whole
$SOC_HOME/Designs/ivm_soc_v1.v
$SOC_HOME/Designs/icebreaker_v1.v
$SOC_HOME/Designs/soc_fpga_v1.v

$SOC_HOME/Designs/ivm_soc_v2.v
# $SOC_HOME/Designs/icebreaker_v2.v
# $SOC_HOME/Designs/soc_fpga_v2.v

### Testbenches that instantiate the Top Level
# $SOC_HOME/Testbenches/soc_tb_v1.sv
$SOC_HOME/Testbenches/soc_fpga_tb_v1.sv
