###################################################################

# Created by write_sdc on Tue Dec 17 21:59:36 2024

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_max_transition 0.15 [current_design]
set_load -pin_load 0.1 [get_ports {data_bus[31]}]
set_load -pin_load 0.1 [get_ports {data_bus[30]}]
set_load -pin_load 0.1 [get_ports {data_bus[29]}]
set_load -pin_load 0.1 [get_ports {data_bus[28]}]
set_load -pin_load 0.1 [get_ports {data_bus[27]}]
set_load -pin_load 0.1 [get_ports {data_bus[26]}]
set_load -pin_load 0.1 [get_ports {data_bus[25]}]
set_load -pin_load 0.1 [get_ports {data_bus[24]}]
set_load -pin_load 0.1 [get_ports {data_bus[23]}]
set_load -pin_load 0.1 [get_ports {data_bus[22]}]
set_load -pin_load 0.1 [get_ports {data_bus[21]}]
set_load -pin_load 0.1 [get_ports {data_bus[20]}]
set_load -pin_load 0.1 [get_ports {data_bus[19]}]
set_load -pin_load 0.1 [get_ports {data_bus[18]}]
set_load -pin_load 0.1 [get_ports {data_bus[17]}]
set_load -pin_load 0.1 [get_ports {data_bus[16]}]
set_load -pin_load 0.1 [get_ports {data_bus[15]}]
set_load -pin_load 0.1 [get_ports {data_bus[14]}]
set_load -pin_load 0.1 [get_ports {data_bus[13]}]
set_load -pin_load 0.1 [get_ports {data_bus[12]}]
set_load -pin_load 0.1 [get_ports {data_bus[11]}]
set_load -pin_load 0.1 [get_ports {data_bus[10]}]
set_load -pin_load 0.1 [get_ports {data_bus[9]}]
set_load -pin_load 0.1 [get_ports {data_bus[8]}]
set_load -pin_load 0.1 [get_ports {data_bus[7]}]
set_load -pin_load 0.1 [get_ports {data_bus[6]}]
set_load -pin_load 0.1 [get_ports {data_bus[5]}]
set_load -pin_load 0.1 [get_ports {data_bus[4]}]
set_load -pin_load 0.1 [get_ports {data_bus[3]}]
set_load -pin_load 0.1 [get_ports {data_bus[2]}]
set_load -pin_load 0.1 [get_ports {data_bus[1]}]
set_load -pin_load 0.1 [get_ports {data_bus[0]}]
set_load -pin_load 0.1 [get_ports {data_addr[31]}]
set_load -pin_load 0.1 [get_ports {data_addr[30]}]
set_load -pin_load 0.1 [get_ports {data_addr[29]}]
set_load -pin_load 0.1 [get_ports {data_addr[28]}]
set_load -pin_load 0.1 [get_ports {data_addr[27]}]
set_load -pin_load 0.1 [get_ports {data_addr[26]}]
set_load -pin_load 0.1 [get_ports {data_addr[25]}]
set_load -pin_load 0.1 [get_ports {data_addr[24]}]
set_load -pin_load 0.1 [get_ports {data_addr[23]}]
set_load -pin_load 0.1 [get_ports {data_addr[22]}]
set_load -pin_load 0.1 [get_ports {data_addr[21]}]
set_load -pin_load 0.1 [get_ports {data_addr[20]}]
set_load -pin_load 0.1 [get_ports {data_addr[19]}]
set_load -pin_load 0.1 [get_ports {data_addr[18]}]
set_load -pin_load 0.1 [get_ports {data_addr[17]}]
set_load -pin_load 0.1 [get_ports {data_addr[16]}]
set_load -pin_load 0.1 [get_ports {data_addr[15]}]
set_load -pin_load 0.1 [get_ports {data_addr[14]}]
set_load -pin_load 0.1 [get_ports {data_addr[13]}]
set_load -pin_load 0.1 [get_ports {data_addr[12]}]
set_load -pin_load 0.1 [get_ports {data_addr[11]}]
set_load -pin_load 0.1 [get_ports {data_addr[10]}]
set_load -pin_load 0.1 [get_ports {data_addr[9]}]
set_load -pin_load 0.1 [get_ports {data_addr[8]}]
set_load -pin_load 0.1 [get_ports {data_addr[7]}]
set_load -pin_load 0.1 [get_ports {data_addr[6]}]
set_load -pin_load 0.1 [get_ports {data_addr[5]}]
set_load -pin_load 0.1 [get_ports {data_addr[4]}]
set_load -pin_load 0.1 [get_ports {data_addr[3]}]
set_load -pin_load 0.1 [get_ports {data_addr[2]}]
set_load -pin_load 0.1 [get_ports {data_addr[1]}]
set_load -pin_load 0.1 [get_ports {data_addr[0]}]
set_load -pin_load 0.1 [get_ports {Destination[31]}]
set_load -pin_load 0.1 [get_ports {Destination[30]}]
set_load -pin_load 0.1 [get_ports {Destination[29]}]
set_load -pin_load 0.1 [get_ports {Destination[28]}]
set_load -pin_load 0.1 [get_ports {Destination[27]}]
set_load -pin_load 0.1 [get_ports {Destination[26]}]
set_load -pin_load 0.1 [get_ports {Destination[25]}]
set_load -pin_load 0.1 [get_ports {Destination[24]}]
set_load -pin_load 0.1 [get_ports {Destination[23]}]
set_load -pin_load 0.1 [get_ports {Destination[22]}]
set_load -pin_load 0.1 [get_ports {Destination[21]}]
set_load -pin_load 0.1 [get_ports {Destination[20]}]
set_load -pin_load 0.1 [get_ports {Destination[19]}]
set_load -pin_load 0.1 [get_ports {Destination[18]}]
set_load -pin_load 0.1 [get_ports {Destination[17]}]
set_load -pin_load 0.1 [get_ports {Destination[16]}]
set_load -pin_load 0.1 [get_ports {Destination[15]}]
set_load -pin_load 0.1 [get_ports {Destination[14]}]
set_load -pin_load 0.1 [get_ports {Destination[13]}]
set_load -pin_load 0.1 [get_ports {Destination[12]}]
set_load -pin_load 0.1 [get_ports {Destination[11]}]
set_load -pin_load 0.1 [get_ports {Destination[10]}]
set_load -pin_load 0.1 [get_ports {Destination[9]}]
set_load -pin_load 0.1 [get_ports {Destination[8]}]
set_load -pin_load 0.1 [get_ports {Destination[7]}]
set_load -pin_load 0.1 [get_ports {Destination[6]}]
set_load -pin_load 0.1 [get_ports {Destination[5]}]
set_load -pin_load 0.1 [get_ports {Destination[4]}]
set_load -pin_load 0.1 [get_ports {Destination[3]}]
set_load -pin_load 0.1 [get_ports {Destination[2]}]
set_load -pin_load 0.1 [get_ports {Destination[1]}]
set_load -pin_load 0.1 [get_ports {Destination[0]}]
set_load -pin_load 0.1 [get_ports {PC[31]}]
set_load -pin_load 0.1 [get_ports {PC[30]}]
set_load -pin_load 0.1 [get_ports {PC[29]}]
set_load -pin_load 0.1 [get_ports {PC[28]}]
set_load -pin_load 0.1 [get_ports {PC[27]}]
set_load -pin_load 0.1 [get_ports {PC[26]}]
set_load -pin_load 0.1 [get_ports {PC[25]}]
set_load -pin_load 0.1 [get_ports {PC[24]}]
set_load -pin_load 0.1 [get_ports {PC[23]}]
set_load -pin_load 0.1 [get_ports {PC[22]}]
set_load -pin_load 0.1 [get_ports {PC[21]}]
set_load -pin_load 0.1 [get_ports {PC[20]}]
set_load -pin_load 0.1 [get_ports {PC[19]}]
set_load -pin_load 0.1 [get_ports {PC[18]}]
set_load -pin_load 0.1 [get_ports {PC[17]}]
set_load -pin_load 0.1 [get_ports {PC[16]}]
set_load -pin_load 0.1 [get_ports {PC[15]}]
set_load -pin_load 0.1 [get_ports {PC[14]}]
set_load -pin_load 0.1 [get_ports {PC[13]}]
set_load -pin_load 0.1 [get_ports {PC[12]}]
set_load -pin_load 0.1 [get_ports {PC[11]}]
set_load -pin_load 0.1 [get_ports {PC[10]}]
set_load -pin_load 0.1 [get_ports {PC[9]}]
set_load -pin_load 0.1 [get_ports {PC[8]}]
set_load -pin_load 0.1 [get_ports {PC[7]}]
set_load -pin_load 0.1 [get_ports {PC[6]}]
set_load -pin_load 0.1 [get_ports {PC[5]}]
set_load -pin_load 0.1 [get_ports {PC[4]}]
set_load -pin_load 0.1 [get_ports {PC[3]}]
set_load -pin_load 0.1 [get_ports {PC[2]}]
set_load -pin_load 0.1 [get_ports {PC[1]}]
set_load -pin_load 0.1 [get_ports {PC[0]}]
create_clock [get_ports clk]  -period 1.43  -waveform {0 0.715}
set_clock_uncertainty 0.15  [get_clocks clk]
set_input_delay -clock clk  0.4  [get_ports rst_n]
set_input_delay -clock clk  0.4  [get_ports {code_bus[31]}]
set_input_delay -clock clk  0.4  [get_ports {code_bus[30]}]
set_input_delay -clock clk  0.4  [get_ports {code_bus[29]}]
set_input_delay -clock clk  0.4  [get_ports {code_bus[28]}]
set_input_delay -clock clk  0.4  [get_ports {code_bus[27]}]
set_input_delay -clock clk  0.4  [get_ports {code_bus[26]}]
set_input_delay -clock clk  0.4  [get_ports {code_bus[25]}]
set_input_delay -clock clk  0.4  [get_ports {code_bus[24]}]
set_input_delay -clock clk  0.4  [get_ports {code_bus[23]}]
set_input_delay -clock clk  0.4  [get_ports {code_bus[22]}]
set_input_delay -clock clk  0.4  [get_ports {code_bus[21]}]
set_input_delay -clock clk  0.4  [get_ports {code_bus[20]}]
set_input_delay -clock clk  0.4  [get_ports {code_bus[19]}]
set_input_delay -clock clk  0.4  [get_ports {code_bus[18]}]
set_input_delay -clock clk  0.4  [get_ports {code_bus[17]}]
set_input_delay -clock clk  0.4  [get_ports {code_bus[16]}]
set_input_delay -clock clk  0.4  [get_ports {code_bus[15]}]
set_input_delay -clock clk  0.4  [get_ports {code_bus[14]}]
set_input_delay -clock clk  0.4  [get_ports {code_bus[13]}]
set_input_delay -clock clk  0.4  [get_ports {code_bus[12]}]
set_input_delay -clock clk  0.4  [get_ports {code_bus[11]}]
set_input_delay -clock clk  0.4  [get_ports {code_bus[10]}]
set_input_delay -clock clk  0.4  [get_ports {code_bus[9]}]
set_input_delay -clock clk  0.4  [get_ports {code_bus[8]}]
set_input_delay -clock clk  0.4  [get_ports {code_bus[7]}]
set_input_delay -clock clk  0.4  [get_ports {code_bus[6]}]
set_input_delay -clock clk  0.4  [get_ports {code_bus[5]}]
set_input_delay -clock clk  0.4  [get_ports {code_bus[4]}]
set_input_delay -clock clk  0.4  [get_ports {code_bus[3]}]
set_input_delay -clock clk  0.4  [get_ports {code_bus[2]}]
set_input_delay -clock clk  0.4  [get_ports {code_bus[1]}]
set_input_delay -clock clk  0.4  [get_ports {code_bus[0]}]
set_input_delay -clock clk  0.4  [get_ports {data_bus[31]}]
set_input_delay -clock clk  0.4  [get_ports {data_bus[30]}]
set_input_delay -clock clk  0.4  [get_ports {data_bus[29]}]
set_input_delay -clock clk  0.4  [get_ports {data_bus[28]}]
set_input_delay -clock clk  0.4  [get_ports {data_bus[27]}]
set_input_delay -clock clk  0.4  [get_ports {data_bus[26]}]
set_input_delay -clock clk  0.4  [get_ports {data_bus[25]}]
set_input_delay -clock clk  0.4  [get_ports {data_bus[24]}]
set_input_delay -clock clk  0.4  [get_ports {data_bus[23]}]
set_input_delay -clock clk  0.4  [get_ports {data_bus[22]}]
set_input_delay -clock clk  0.4  [get_ports {data_bus[21]}]
set_input_delay -clock clk  0.4  [get_ports {data_bus[20]}]
set_input_delay -clock clk  0.4  [get_ports {data_bus[19]}]
set_input_delay -clock clk  0.4  [get_ports {data_bus[18]}]
set_input_delay -clock clk  0.4  [get_ports {data_bus[17]}]
set_input_delay -clock clk  0.4  [get_ports {data_bus[16]}]
set_input_delay -clock clk  0.4  [get_ports {data_bus[15]}]
set_input_delay -clock clk  0.4  [get_ports {data_bus[14]}]
set_input_delay -clock clk  0.4  [get_ports {data_bus[13]}]
set_input_delay -clock clk  0.4  [get_ports {data_bus[12]}]
set_input_delay -clock clk  0.4  [get_ports {data_bus[11]}]
set_input_delay -clock clk  0.4  [get_ports {data_bus[10]}]
set_input_delay -clock clk  0.4  [get_ports {data_bus[9]}]
set_input_delay -clock clk  0.4  [get_ports {data_bus[8]}]
set_input_delay -clock clk  0.4  [get_ports {data_bus[7]}]
set_input_delay -clock clk  0.4  [get_ports {data_bus[6]}]
set_input_delay -clock clk  0.4  [get_ports {data_bus[5]}]
set_input_delay -clock clk  0.4  [get_ports {data_bus[4]}]
set_input_delay -clock clk  0.4  [get_ports {data_bus[3]}]
set_input_delay -clock clk  0.4  [get_ports {data_bus[2]}]
set_input_delay -clock clk  0.4  [get_ports {data_bus[1]}]
set_input_delay -clock clk  0.4  [get_ports {data_bus[0]}]
set_output_delay -clock clk  0.4  [get_ports {data_bus[31]}]
set_output_delay -clock clk  0.4  [get_ports {data_bus[30]}]
set_output_delay -clock clk  0.4  [get_ports {data_bus[29]}]
set_output_delay -clock clk  0.4  [get_ports {data_bus[28]}]
set_output_delay -clock clk  0.4  [get_ports {data_bus[27]}]
set_output_delay -clock clk  0.4  [get_ports {data_bus[26]}]
set_output_delay -clock clk  0.4  [get_ports {data_bus[25]}]
set_output_delay -clock clk  0.4  [get_ports {data_bus[24]}]
set_output_delay -clock clk  0.4  [get_ports {data_bus[23]}]
set_output_delay -clock clk  0.4  [get_ports {data_bus[22]}]
set_output_delay -clock clk  0.4  [get_ports {data_bus[21]}]
set_output_delay -clock clk  0.4  [get_ports {data_bus[20]}]
set_output_delay -clock clk  0.4  [get_ports {data_bus[19]}]
set_output_delay -clock clk  0.4  [get_ports {data_bus[18]}]
set_output_delay -clock clk  0.4  [get_ports {data_bus[17]}]
set_output_delay -clock clk  0.4  [get_ports {data_bus[16]}]
set_output_delay -clock clk  0.4  [get_ports {data_bus[15]}]
set_output_delay -clock clk  0.4  [get_ports {data_bus[14]}]
set_output_delay -clock clk  0.4  [get_ports {data_bus[13]}]
set_output_delay -clock clk  0.4  [get_ports {data_bus[12]}]
set_output_delay -clock clk  0.4  [get_ports {data_bus[11]}]
set_output_delay -clock clk  0.4  [get_ports {data_bus[10]}]
set_output_delay -clock clk  0.4  [get_ports {data_bus[9]}]
set_output_delay -clock clk  0.4  [get_ports {data_bus[8]}]
set_output_delay -clock clk  0.4  [get_ports {data_bus[7]}]
set_output_delay -clock clk  0.4  [get_ports {data_bus[6]}]
set_output_delay -clock clk  0.4  [get_ports {data_bus[5]}]
set_output_delay -clock clk  0.4  [get_ports {data_bus[4]}]
set_output_delay -clock clk  0.4  [get_ports {data_bus[3]}]
set_output_delay -clock clk  0.4  [get_ports {data_bus[2]}]
set_output_delay -clock clk  0.4  [get_ports {data_bus[1]}]
set_output_delay -clock clk  0.4  [get_ports {data_bus[0]}]
set_output_delay -clock clk  0.4  [get_ports {data_addr[31]}]
set_output_delay -clock clk  0.4  [get_ports {data_addr[30]}]
set_output_delay -clock clk  0.4  [get_ports {data_addr[29]}]
set_output_delay -clock clk  0.4  [get_ports {data_addr[28]}]
set_output_delay -clock clk  0.4  [get_ports {data_addr[27]}]
set_output_delay -clock clk  0.4  [get_ports {data_addr[26]}]
set_output_delay -clock clk  0.4  [get_ports {data_addr[25]}]
set_output_delay -clock clk  0.4  [get_ports {data_addr[24]}]
set_output_delay -clock clk  0.4  [get_ports {data_addr[23]}]
set_output_delay -clock clk  0.4  [get_ports {data_addr[22]}]
set_output_delay -clock clk  0.4  [get_ports {data_addr[21]}]
set_output_delay -clock clk  0.4  [get_ports {data_addr[20]}]
set_output_delay -clock clk  0.4  [get_ports {data_addr[19]}]
set_output_delay -clock clk  0.4  [get_ports {data_addr[18]}]
set_output_delay -clock clk  0.4  [get_ports {data_addr[17]}]
set_output_delay -clock clk  0.4  [get_ports {data_addr[16]}]
set_output_delay -clock clk  0.4  [get_ports {data_addr[15]}]
set_output_delay -clock clk  0.4  [get_ports {data_addr[14]}]
set_output_delay -clock clk  0.4  [get_ports {data_addr[13]}]
set_output_delay -clock clk  0.4  [get_ports {data_addr[12]}]
set_output_delay -clock clk  0.4  [get_ports {data_addr[11]}]
set_output_delay -clock clk  0.4  [get_ports {data_addr[10]}]
set_output_delay -clock clk  0.4  [get_ports {data_addr[9]}]
set_output_delay -clock clk  0.4  [get_ports {data_addr[8]}]
set_output_delay -clock clk  0.4  [get_ports {data_addr[7]}]
set_output_delay -clock clk  0.4  [get_ports {data_addr[6]}]
set_output_delay -clock clk  0.4  [get_ports {data_addr[5]}]
set_output_delay -clock clk  0.4  [get_ports {data_addr[4]}]
set_output_delay -clock clk  0.4  [get_ports {data_addr[3]}]
set_output_delay -clock clk  0.4  [get_ports {data_addr[2]}]
set_output_delay -clock clk  0.4  [get_ports {data_addr[1]}]
set_output_delay -clock clk  0.4  [get_ports {data_addr[0]}]
set_output_delay -clock clk  0.4  [get_ports {Destination[31]}]
set_output_delay -clock clk  0.4  [get_ports {Destination[30]}]
set_output_delay -clock clk  0.4  [get_ports {Destination[29]}]
set_output_delay -clock clk  0.4  [get_ports {Destination[28]}]
set_output_delay -clock clk  0.4  [get_ports {Destination[27]}]
set_output_delay -clock clk  0.4  [get_ports {Destination[26]}]
set_output_delay -clock clk  0.4  [get_ports {Destination[25]}]
set_output_delay -clock clk  0.4  [get_ports {Destination[24]}]
set_output_delay -clock clk  0.4  [get_ports {Destination[23]}]
set_output_delay -clock clk  0.4  [get_ports {Destination[22]}]
set_output_delay -clock clk  0.4  [get_ports {Destination[21]}]
set_output_delay -clock clk  0.4  [get_ports {Destination[20]}]
set_output_delay -clock clk  0.4  [get_ports {Destination[19]}]
set_output_delay -clock clk  0.4  [get_ports {Destination[18]}]
set_output_delay -clock clk  0.4  [get_ports {Destination[17]}]
set_output_delay -clock clk  0.4  [get_ports {Destination[16]}]
set_output_delay -clock clk  0.4  [get_ports {Destination[15]}]
set_output_delay -clock clk  0.4  [get_ports {Destination[14]}]
set_output_delay -clock clk  0.4  [get_ports {Destination[13]}]
set_output_delay -clock clk  0.4  [get_ports {Destination[12]}]
set_output_delay -clock clk  0.4  [get_ports {Destination[11]}]
set_output_delay -clock clk  0.4  [get_ports {Destination[10]}]
set_output_delay -clock clk  0.4  [get_ports {Destination[9]}]
set_output_delay -clock clk  0.4  [get_ports {Destination[8]}]
set_output_delay -clock clk  0.4  [get_ports {Destination[7]}]
set_output_delay -clock clk  0.4  [get_ports {Destination[6]}]
set_output_delay -clock clk  0.4  [get_ports {Destination[5]}]
set_output_delay -clock clk  0.4  [get_ports {Destination[4]}]
set_output_delay -clock clk  0.4  [get_ports {Destination[3]}]
set_output_delay -clock clk  0.4  [get_ports {Destination[2]}]
set_output_delay -clock clk  0.4  [get_ports {Destination[1]}]
set_output_delay -clock clk  0.4  [get_ports {Destination[0]}]
set_output_delay -clock clk  0.4  [get_ports {PC[31]}]
set_output_delay -clock clk  0.4  [get_ports {PC[30]}]
set_output_delay -clock clk  0.4  [get_ports {PC[29]}]
set_output_delay -clock clk  0.4  [get_ports {PC[28]}]
set_output_delay -clock clk  0.4  [get_ports {PC[27]}]
set_output_delay -clock clk  0.4  [get_ports {PC[26]}]
set_output_delay -clock clk  0.4  [get_ports {PC[25]}]
set_output_delay -clock clk  0.4  [get_ports {PC[24]}]
set_output_delay -clock clk  0.4  [get_ports {PC[23]}]
set_output_delay -clock clk  0.4  [get_ports {PC[22]}]
set_output_delay -clock clk  0.4  [get_ports {PC[21]}]
set_output_delay -clock clk  0.4  [get_ports {PC[20]}]
set_output_delay -clock clk  0.4  [get_ports {PC[19]}]
set_output_delay -clock clk  0.4  [get_ports {PC[18]}]
set_output_delay -clock clk  0.4  [get_ports {PC[17]}]
set_output_delay -clock clk  0.4  [get_ports {PC[16]}]
set_output_delay -clock clk  0.4  [get_ports {PC[15]}]
set_output_delay -clock clk  0.4  [get_ports {PC[14]}]
set_output_delay -clock clk  0.4  [get_ports {PC[13]}]
set_output_delay -clock clk  0.4  [get_ports {PC[12]}]
set_output_delay -clock clk  0.4  [get_ports {PC[11]}]
set_output_delay -clock clk  0.4  [get_ports {PC[10]}]
set_output_delay -clock clk  0.4  [get_ports {PC[9]}]
set_output_delay -clock clk  0.4  [get_ports {PC[8]}]
set_output_delay -clock clk  0.4  [get_ports {PC[7]}]
set_output_delay -clock clk  0.4  [get_ports {PC[6]}]
set_output_delay -clock clk  0.4  [get_ports {PC[5]}]
set_output_delay -clock clk  0.4  [get_ports {PC[4]}]
set_output_delay -clock clk  0.4  [get_ports {PC[3]}]
set_output_delay -clock clk  0.4  [get_ports {PC[2]}]
set_output_delay -clock clk  0.4  [get_ports {PC[1]}]
set_output_delay -clock clk  0.4  [get_ports {PC[0]}]
set_drive 0.0001  [get_ports rst_n]
